name = "zhoplist-api"
main = "src/index.ts"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# Local development server configuration
[dev]
port = 8787

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "zhoplist-db"
database_id = "0dd7bd8c-7e0c-422b-b143-5b75188d5996"

# CORS headers for API
[env.production.vars]
ENVIRONMENT = "production"
