name = "zhoplist-api"
main = "src/index.ts"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "zhoplist-db"
database_id = "67ba17d9-2882-46dd-aa37-c5e8f9971907"

# CORS headers for API
[env.production.vars]
ENVIRONMENT = "production"
